# vim: set filetype=zsh :
# Environment for all shells (SSH commands, scripts, interactive)

# Locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Editor
export VISUAL=nvim
export EDITOR=$VISUAL
export MANPAGER="nvim -c 'set ft=man' -"

# Homebrew environment
if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# Homebrew behavior
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_UPGRADE_CLEANUP=1
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
export HOMEBREW_NO_ENV_HINTS=1

typeset -U path
path=(
  "$HOME/.bun/bin"
  "$HOME/.local/bin"
  "$HOME/.docker/bin"
  $path
)

# Ripgrep config path
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

# ASDF version manager
if [[ -f /opt/homebrew/opt/asdf/libexec/asdf.sh ]]; then
    source /opt/homebrew/opt/asdf/libexec/asdf.sh
elif [[ -f /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh ]]; then
    source /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh
fi

# FZF defaults (used by vim plugins, git tools, etc.)
export BAT_THEME="TwoDark"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'
export FZF_COLORS="fg:-1,bg:-1,hl:230,fg+:3,bg+:233,hl+:229,info:150,prompt:110,spinner:150,pointer:167,marker:174"
export FZF_DEFAULT_OPTS="--color=$FZF_COLORS --height=40% --layout=reverse --border --bind='ctrl-/:toggle-preview'"

# Platform-specific environment
[[ -f $HOME/.zshenv.mac ]] && source $HOME/.zshenv.mac

# 1Password SSH agent (unless forwarded agent is present)
# Forwarded agents have paths like /tmp/ssh-XXXXX/agent.PID
if [[ ! "$SSH_AUTH_SOCK" =~ /ssh-.*/agent ]]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  else
    export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
  fi
fi